Added Front End
Adnanhoq/CrimeLineLocal pull request #1
Opened 2024-10-21 13:31 UTC by Adnanhoq

This PR encompasses the following tickets:
[- Set up Repo](https://kainossoftware.atlassian.net/browse/GAIBP-47)
[- File Upload](https://kainossoftware.atlassian.net/browse/GAIBP-46)

2024-10-21 14:09 UTC, Jack-M1 approved these changes

2024-10-21 14:34 UTC, Adnanhoq commented
<img width="1509" alt="Screenshot 2024-10-21 at 13 53 32" src="https://github.com/user-attachments/assets/4b92f493-adab-475e-9db7-dfa617dd21d3">
<img width="1509" alt="Screenshot 2024-10-21 at 15 33 37" src="https://github.com/user-attachments/assets/3708d16e-8843-422c-9934-fd9f7a9f6fd7">
<img width="1509" alt="Screenshot 2024-10-21 at 15 33 54" src="https://github.com/user-attachments/assets/2d4bf24f-9e73-45c8-9127-c0b99f782ef6">
<img width="1509" alt="Screenshot 2024-10-21 at 15 33 58" src="https://github.com/user-attachments/assets/f590077f-f263-411e-af82-933374a67101">
<img width="1509" alt="Screenshot 2024-10-21 at 15 34 04" src="https://github.com/user-attachments/assets/8b620856-4f05-4310-88a7-700c51ad1841">

2024-10-21 16:47 UTC, Leebee1392 requested changes

2024-10-21 16:47 UTC, Leebee1392 commented on CrimeLineFrontEnd/src/assets/favicon_io/favicon.ico
Remove

2024-10-22 07:29 UTC, Adnanhoq commented on CrimeLineFrontEnd/src/assets/favicon_io/favicon.ico
Removed

2024-10-22 08:04 UTC, Leebee1392 approved these changes

2024-10-23 15:39 UTC, Leebee1392 requested changes

2024-10-23 15:39 UTC, Leebee1392 commented on .gitignore
> +# Logs
Why are there two .gitignores

2024-10-23 15:39 UTC, Leebee1392 commented on CrimeLineFrontEnd/eslint.config.mjs
> +// import globals from "globals";
If they are all commented out, shouldn't the file just be deleted

2024-10-23 15:39 UTC, Leebee1392 commented on CrimeLineFrontEnd/src/vite-env.d.ts
> +/// <reference types="vite/client" />
Is this needed?

2024-10-24 07:49 UTC, Leebee1392 approved these changes

2024-10-24 14:13 UTC, merged